.. -*- rst -*-

Versions
========

.. rest_method:: GET /

This endpoint is used to get the list of api versions. There is no authentication required.

.. rest_status_code:: success ../http-status.yaml

   - 200

.. rest_status_code:: error ../http-status.yaml

   - 400

Request
-------

N/A

Curl Example
------------

.. literalinclude:: examples/versions-get-curl
   :language: bash

Response Parameters
-------------------

N/A

